services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  W3code\W3cAIConnector\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  W3code\W3cAIConnector\Service\SolrService:
    public: true
    shared: false
